# Generated by Django 4.2.16 on 2024-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='Apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='Direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='Especialidad',
            field=models.CharField(max_length=50, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='Nombres',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='Telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
