# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumExamen', models.IntegerField(verbose_name='NumExamen')),
                ('Nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('FecExamen', models.DateField(verbose_name='FecExamen')),
                ('Resultado', models.CharField(max_length=60, verbose_name='Resultado')),
                ('Descripcion', models.CharField(max_length=60, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='DetalleExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoExamen', models.CharField(max_length=60, verbose_name='TipoExamen')),
                ('Estado', models.CharField(max_length=60, verbose_name='Estado')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo')),
                ('Observacion', models.CharField(max_length=60, verbose_name='Observacion')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name_plural': 'Detalleexamen',
            },
        ),
    ]
