# Generated by Django 4.2.16 on 2024-11-12 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0002_alter_medicos_apellidos_alter_medicos_direccion_and_more'),
        ('Pacientes', '0001_initial'),
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='medicos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Medicos.medicos', verbose_name='Medicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Pacientes.pacientes', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
