# Generated by Django 4.2.16 on 2024-11-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0002_alter_medicos_apellidos_alter_medicos_direccion_and_more'),
        ('Examen', '0003_alter_examen_options_remove_examen_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Medicos.medicos'),
        ),
    ]
