# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('Descripcion', models.TextField(max_length=60, verbose_name='Descripcion')),
                ('Estatus', models.CharField(max_length=60, verbose_name='Estatus')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('FechaModificacion', models.DateField(verbose_name='FechaModificacion')),
                ('medicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicos.medicos', verbose_name='Medicos')),
            ],
            options={
                'verbose_name_plural': 'Especialidad',
            },
        ),
    ]
