# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('Unidad', models.IntegerField()),
                ('Interpretacion', models.IntegerField()),
                ('FecResultado', models.IntegerField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name_plural': 'ResultadosExamenes',
            },
        ),
    ]
