# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('UnidadMedida', models.CharField(max_length=60, verbose_name='UnidadMedida')),
                ('ValorReferenciaMax', models.CharField(max_length=60, verbose_name='ValorReferenciaMax')),
                ('ValorReferenciaMin', models.CharField(max_length=60, verbose_name='ValorReferenciaMin')),
                ('Descripcion', models.CharField(max_length=60, verbose_name='Descripcion')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name_plural': 'Indicador',
            },
        ),
    ]
