# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enfermedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipo', models.CharField(max_length=100, verbose_name='NombreTipo')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enfermedad.enfermedad', verbose_name='Enfermedad')),
            ],
            options={
                'verbose_name_plural': 'TiposEnfermedades',
            },
        ),
    ]
