# Generated by Django 4.2.16 on 2024-11-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0001_initial'),
        ('Pacientes', '0001_initial'),
        ('Examen', '0001_initial'),
        ('Medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_citas', models.CharField(max_length=50, verbose_name='Num_citas')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('Razon', models.CharField(max_length=50, verbose_name='Razon')),
                ('Estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('Costo', models.CharField(max_length=50, verbose_name='Costo')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Examen.examen', verbose_name='Examen')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Medicamento.medicamento', verbose_name='Medicamento')),
                ('medicos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Medicos.medicos', verbose_name='Medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pacientes.pacientes', verbose_name='Paciente')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='DetalleCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnostico', models.CharField(max_length=100)),
                ('Tratamiento', models.CharField(max_length=100)),
                ('citas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Citas.citas', verbose_name='Citas')),
            ],
            options={
                'verbose_name_plural': 'DetalleCitas',
            },
        ),
    ]
